# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  omniauth_facebook_provider_key: <%= ENV["FACEBOOK_APP_ID"] %>
  omniauth_facebook_provider_secret: <%= ENV["FACEBOOK_SECRET"] %>
  omniauth_twitter_provider_key: <%= ENV["TWITTER_APP_ID"] %>
  omniauth_twitter_provider_secret: <%= ENV["TWITTER_SECRET"] %>
  omniauth_google_provider_key: <%= ENV["GOOGLE_APP_ID"] %>
  omniauth_google_provider_secret: <%= ENV["GOOGLE_SECRET"] %>   
  
  domain_name: localhost
  secret_key_base: ab5bd2ca4798a4c82d3e0b2318eaf3e49904152cbe1a4e6530f9dafc83d62f5596e913dbf93d9a6a91d819da3865370a335beb0303e1699161279fcbda01183e

test:
  secret_key_base: b39bd0fc8f99848de44ecdc0280672c1e067d7dcca94b8905c50938e779cf65f9e8f1bab252528aa319c394ec36cb24441867210f2a8427ed935ced8ef0e46f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  omniauth_facebook_provider_key: <%= ENV["FACEBOOK_APP_ID"] %>
  omniauth_facebook_provider_secret: <%= ENV["FACEBOOK_SECRET"] %>
  omniauth_twitter_provider_key: <%= ENV["TWITTER_APP_ID"] %>
  omniauth_twitter_provider_secret: <%= ENV["TWITTER_SECRET"] %>
  omniauth_google_provider_key: <%= ENV["GOOGLE_APP_ID"] %>
  omniauth_google_provider_secret: <%= ENV["GOOGLE_SECRET"] %>   
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
